id: marketing_roi_chart
namespace: shiny_rocks
description: |
  After dbt transformation, we use marketing data joined to orders to create a plot of marketing ROI.
  The flow first query data from BigQuery and then run a Python script to read data and create a chart out of it.
  Then it sends this chart by email to the marketing team.

labels:
  tag: marketing

tasks:
  - id: get_data
    type: io.kestra.plugin.gcp.bigquery.Query
    serviceAccount: '{{ secret("GCP_CREDS") }}'
    projectId: kestra-dev
    sql: "{{ render(read('scripts/marketing/query/get_data.sql')) }}"
    store: true
  
  - id: to_csv
    type: io.kestra.plugin.serdes.csv.CsvWriter
    from: "{{ outputs.get_data.uri }}"

  - id: python
    type: io.kestra.plugin.scripts.python.Script
    warningOnStdErr: false
    docker:
      image: ghcr.io/kestra-io/pydata
    beforeCommands:
      - pip install plotnine
    script: "{{ read('scripts/marketing/src/plot.py') }}"
    inputFiles:
      data.csv: "{{ outputs.to_csv.uri }}"
    outputFiles:
      - plot.png
    

  - id: send_email
    disabled: true
    type: io.kestra.plugin.notifications.mail.MailSend
    attachments:
      - name: plot.png
        uri: '{{ outputs.python.outputFiles["plot.png"] }}'
    subject: "Daily marketing ROI"
    to: "marketing@shinyrocks.com"
    htmlTextContent: |
      Here is the last marketing ROI data!


triggers:

  - id: get_data
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionFlowCondition
        namespace: shiny_rocks
        flowId: dbt_run
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - SUCCESS

