id: marketing_investments_to_bigquery
namespace: shiny_rocks
description: |
  The marketing teams manage their investments into a Google Spreadsheet, hence we load those data into BigQuery for further processing and join with other data.

labels:
  tag: marketing

variables:
  spreadsheet_id: 1C0UWuMuiEIxkOKzSQhbhFn6AILzmXX59NUbtI4s3wpU
  dataset_table: shiny_rocks.marketing_investments

tasks:
  - id: read_gsheet
    type: io.kestra.plugin.googleworkspace.sheets.Read
    description: Read data from Google Spreadsheet
    serviceAccount: "{{ secret('GCP_CREDS') }}"
    spreadsheetId: "{{ vars.spreadsheet_id }}"
    store: true
    valueRender: FORMATTED_VALUE
  
  - id: write_csv
    type: io.kestra.plugin.serdes.csv.IonToCsv
    description: Write CSV into Kestra internal storage
    from: "{{ outputs.read_gsheet.uris.marketing }}"
  
  - id: load_biqquery
    type: io.kestra.plugin.gcp.bigquery.Load
    description: Load data into BigQuery
    serviceAccount: "{{ secret('GCP_CREDS') }}"
    autodetect: true
    writeDisposition: WRITE_TRUNCATE
    csvOptions:
      fieldDelimiter: ","
    projectId: "kestra-sandbox"
    destinationTable: '{{ vars.dataset_table }}'
    format: CSV
    from: "{{ outputs.write_csv.uri }}"

triggers:
  - id: schedule
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 10 * * *"
