id: produce_data
namespace: shiny_rocks
description: |
  This flow generate Shiny Rocks fictional data. Three datasets are created: `orders`, `payments` and `services`.
  Like in reality, those data change everyday.

labels:
  tag: producer

tasks:

      - id: python
        type: io.kestra.plugin.scripts.python.Commands
        namespaceFiles:
          enabled: true
        warningOnStdErr: false
        beforeCommands:
          - pip install -r scripts/produce/requirements.txt
        commands:
          - python scripts/produce/produce_data.py --date {{ schedule.date ?? now() | date("yyyy-MM-dd")}}
        outputFiles:
          - '*.csv'

      - id: run_date
        type: io.kestra.core.tasks.debugs.Return
        format: '{{ schedule.date ?? now() | date("yyyy-MM-dd")}}'


triggers:
  - id: schedule_produce_data
    type: io.kestra.core.models.triggers.types.Schedule
    cron: "0 10 * * *"
    backfill:
      start: 2024-01-01T10:00:00Z

