id: slack_failure_alert
namespace: shiny_rocks
description: |
  This flow send a Slack notificiation whenever a flow execution in the `shiny_rocks` namespace end up in FAILED or WARNING state.

labels:
  tag: alerting

tasks:
  - id: send
    type: io.kestra.plugin.notifications.slack.SlackExecution
    disabled: true
    url: "{{ secret('SLACK_WEBHOOK') }}"
    channel: "#general"
    executionId: "{{trigger.executionId}}"

triggers:
  - id: listen
    type: io.kestra.core.models.triggers.types.Flow
    conditions:
      - type: io.kestra.core.models.conditions.types.ExecutionStatusCondition
        in:
          - FAILED
          - WARNING
      - type: io.kestra.core.models.conditions.types.ExecutionNamespaceCondition
        namespace: shiny_rocks
        prefix: true